### ISSUE TITLE
Has get_stimulus_design_matrix been deprecated?

### ISSUE THREAD

**Issue by jsiegle** [berenslab/RFEst#3]
Thanks for making this library public, it's super helpful!

The example notebooks try to import `get_stimulus_design_matrix`, but it seems like the name of this function has been changed to `build_design_matrix.` Is this correct? If so, can you update the notebooks to reflect this change?

**Comment by huangziwei** [comment]
Yes, `get_stimulus_design_matrix ` has been renamed to `build_design_matrix`. Sorry for that. All notebooks are updated now.
