### ISSUE TITLE
Jax lib version not available anymore

### ISSUE THREAD

**Issue by marcbue** [berenslab/RFEst#6]
Hi,

I wanted to try out the package but unfortunately the jaxlib version specified in the requirements is not available on Pypi anymore. using a newer one leads to an error that a function is missing in jaxlib.

**Comment by huangziwei** [comment]
Hi.

I just removed the versions restriction for both Jax and jaxlib. 

They were restricted to older versions because a bug in the newer versions that make the computation significantly slower on the CPU. I just tested with the latest versions of them and now it works fine.
